config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/chat' => 'chat#index'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController 
  def index

  end
end

app/controllers/chat_socket_controller.rb
class ChatSocketController < WebsocketRails::BaseController

  # The initialize_session method will be called the first time a controller is subscribed to an event in the event router.
  # Values added to the controller data store from inside the initialize_session method will be available throughout the course of the server lifetime.
  def initialize_session
    controller_store[:users_count] = 0
  end

  def new_message
    broadcast_message :new_message, {message: "#{message[:message]}", datetime: "#{message[:datetime]}", user_name: "#{message[:user_name]}"}
  end

  # Un usuario se ha conectado al chat
  # Action provided by websockets rails fired when user subscribe to channel
  def client_connected
    # incrementamos contadores
    if !controller_store[:users_count].blank?
      controller_store[:users_count] += 1
    else
      controller_store[:users_count] = 0
    end
    # Se notifica a todos los conectados por multidifusión
    logger.debug message.inspect
    broadcast_message :users_count_changed, {users_count: controller_store[:users_count]}
    # Se notifica al usuario que se acaba de conectar
    send_message :connection_success, {message: 'Conexión ok. Habla ahora o calla para siempre.'}
  end

  # Un usuario se ha desconectado del chat porque ha abandonado la página
  # Action provided by websockets rails fired when user unsubscribe to channel
  def client_disconnected
    if !controller_store[:users_count].blank?
      controller_store[:users_count] -= 1
    else
      controller_store[:users_count] = 0
    end
    # Se notifica al resto de usuarios conectados de que hay un usuario menos en el chat
    broadcast_message :users_count_changed, {users_count: controller_store[:users_count]}
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/chat_socket_helper.rb
module ChatSocketHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/chat/_message.html.haml
%li.left.clearfix
  .chat-body.clearfix
    .header
      %strong.primary-font Jack Sparrow
      %small.pull-right.text-muted
        %span.glyphicon.glyphicon-time
        12 mins ago
    %p
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur bibendum ornare
      dolor, quis ullamcorper ligula sodales.
  %hr

app/views/chat/index.html.haml
%h1.text-center Chat con WebSockets
.col-xs-12.col-sm-10.col-sm-offset-1.col-md-8.col-md-offset-2.col-lg-6.col-lg-offset-3
  .text-right
    %small#connected_users_count
  .panel.panel-primary
    #accordion.panel-heading
      .input-group
        .input-group-addon
          .glyphicon.glyphicon-comment
        =text_field_tag 'name_input', '', placeholder: 'Elige un nombre chulo', class: 'form-control input-sm', required: true, onkeyup: "window.websocketsExample.enable_to_send();"
        %span.input-group-btn
          #btn_connect_chat.btn.btn-warning.btn-sm.disabled{onclick: "window.websocketsExample.start()"}
            Conectar
    .panel-body
      %ul.chat#chat_messages_index
    .panel-footer
      .input-group
        =text_field_tag 'message_input', '', placeholder: 'Escribe un mensaje original', class: 'form-control input-sm', required: true, disabled: true
        %span.input-group-btn
          #btn_send_chat.btn.btn-warning.btn-sm.disabled{onclick: "window.websocketsExample.send_message($('#message_input').val())"}
            Enviar
  %small#message_status
  .text-right
    %small
      Gracias a
      %span
        =link_to('simolation', 'http://bootsnipp.com/Simolation', target: '_blank')
      por el 
      %span
        =link_to('snippet', 'http://bootsnipp.com/snippets/featured/collapsible-chat-widget', target: '_blank')
      de Bootstrap
:javascript
  window.websocketsExample.init("#{DOMINIO}");

app/views/layouts/_messages.html.haml
-# app/views/layouts/_messages.html.haml
.flashes_container
  - flash.each do |name, msg|
    - if msg.is_a?(String)
      .alert-dismissible{:class => "alert alert-#{name.to_sym == :notice ? "success" : "danger"}"}
        %a.close{"data-dismiss" => "alert"} ×
        = content_tag :div, msg, :id => "flash_#{name}"
  :javascript
    setTimeout( "jQuery('.flashes_container').slideUp('fast', function(){$(this).remove();});", 3000 );

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Websockets chat example"
    %meta{:content => content_for?(:description) ? yield(:description) : "Ejemplo de aplicación construida con Ruby on Rails en la que se implementa un chat utilizando websockets. Desarrollada por Daniel Romero @danielRomeroE. Web app example of chat made with websockets and ruby on rails by Daniel Romero @danielRomeroE", :name => "description"}
    = stylesheet_link_tag :application, :media => "all"
    = javascript_include_tag :application
    %link{href: "//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css", rel: "stylesheet"}/
    %link{href: "//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css", rel: "stylesheet"}/
    = csrf_meta_tags
    = yield(:head)
  %body
    %nav.navbar.navbar-inverse
      .navbar-header
        =link_to('WebSocket example', root_path, class: 'navbar-brand')
      
    #main
      .container
        .content
          .row
            .col-xs-12.col-sm-12.col-md-8.col-md-offset-2.col-lg-6.col-lg-offset-3
              #application_flashes
                = render 'layouts/messages'
            .col-xs-12.col-sm-12.col-md-12.col-lg-12
              #application_content
                = yield
          %footer

app/views/welcome/index.html.haml
.jumbotron
  %h1 Hello, world!
  %p Ejemplo de Websockets para Betabeers Guadalajara
  =link_to('https://github.com/danielRomero', target: '_blank') do
    .btn.btn-primary.btn-lg{style: 'margin-top: 15px;'}
      .fa.fa-github
      danielRomero
  =link_to('https://twitter.com/DanielRomeroE', target: '_blank') do
    .btn.btn-primary.btn-lg{style: 'margin-top: 15px;'}
      .fa.fa-twitter
      @danielRomeroE
.text-center
  =link_to(chat_path,class: 'btn btn-lg btn-success btn-block') do
    Entrar